#!/usr/bin/env bash
set -e

this_dir="$(readlink -f "$(dirname "$0")")"

export LD_LIBRARY_PATH="$this_dir/usr/lib:${LD_LIBRARY_PATH}"
export QT_PLUGIN_PATH="$this_dir/usr/plugins:${QT_PLUGIN_PATH}"
export QML2_IMPORT_PATH="$this_dir/usr/qml:${QML2_IMPORT_PATH}"

if [ -f "$this_dir/apprun-hooks/linuxdeploy-plugin-qt-hook.sh" ]; then
    source "$this_dir/apprun-hooks/linuxdeploy-plugin-qt-hook.sh"
fi

for host_qt_plugins in /usr/lib/qt6/plugins /usr/lib64/qt6/plugins /usr/lib/x86_64-linux-gnu/qt6/plugins; do
    if [ -d "$host_qt_plugins" ]; then
        export QT_PLUGIN_PATH="${QT_PLUGIN_PATH}:$host_qt_plugins"
    fi
done

exec "$this_dir/usr/bin/omikuji" "$@"
